/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Camera.glb
*/
import React, { useEffect, useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { Canvas, useFrame, useThree } from '@react-three/fiber'

export default function Camera(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/Camera.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions['CameraAction'].play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera
          name="Camera"
          makeDefault={true}
          far={1000}
          near={0.1}
          fov={26.23}
          position={[9.86, 6.94, 26.72]}
          rotation={[-0.26, 0.55, 0.11]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/Camera.glb')
