/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Ground.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/Ground-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ground_Baked001.geometry} material={materials.Material} scale={1.25} />
    </group>
  )
}

useGLTF.preload('models/Ground-transformed.glb')
