/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Hand.glb --transform -R 512
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Hand(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('https://hauntedhouse2023.netlify.app/models/Hand-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.action1.play()
    actions.action2.play()

  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="GLOBAL_MAIN_CONTROL_R" position={[-1.57, -6.1, 1.09]} rotation={[Math.PI / 2, 0, 0.37]} scale={0.47}>
          <group name="GLOBAL_cntrl">
            <group name="Armature004">
              <primitive object={nodes.Root_joint} />
              <primitive object={nodes.neutral_bone} />
              <skinnedMesh name="Hand_Low_Baked" geometry={nodes.Hand_Low_Baked.geometry} material={materials.Hand_Low_Baked} skeleton={nodes.Hand_Low_Baked.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://hauntedhouse2023.netlify.app/models/Hand-transformed.glb')
